print("Here are some of my favorite books:")
print("'The House in the Cerulean Sea,' by TJ Klune")
print("'They Both Die at the End,' by Adam Silvera")
print("'Illuminae,' by Amie Kaufman and Jay Kristoff")
print("'Six Wakes,' by Mur Lafferty")
print("'The Metamorphosis,' by Franz Kafka")
print("'I am Number Four,' by Pittacus Lore")
print("'Six of Crows,' by Leigh Bardugo")
print("'Fruits Basket,' by Natsuki Takaya")
print("'Percy Jackson,' by Rick Riordan")